networks:
  fukuyoka:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  fukuyoka_app:
    image: fukuyoka_app:latest
    build:
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    container_name: fukuyoka_app
    init: true
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "/app/target/release/api || (cargo build --release && /app/target/release/api)"
    restart: unless-stopped
    networks:
      - fukuyoka

  fukuyoka_frontend:
    image: docker.io/hugomods/hugo:latest
    container_name: fukuyoka_frontend
    working_dir: /src
    env_file:
      - .env
    environment:
      HUGO_ENV: production
      DOMAIN: ${DOMAIN}
    command: --minify
    volumes:
      - ./frontend:/src
    restart: "no"
    networks:
      - fukuyoka

  fukuyoka_proxy:
    image: nginx:latest
    container_name: fukuyoka_proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/teapot.html:/etc/nginx/html/teapot.html:ro
      - ./frontend/public:/var/www/hugo:ro
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      start_period: 10s # DBやAPIの起動を待つための猶予期間
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      fukuyoka_frontend:
        condition: service_completed_successfully
      fukuyoka_app:
        condition: service_started
    networks:
      fukuyoka:
        ipv4_address: 192.168.100.10

  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: cloudflared
    env_file:
      - .env
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      fukuyoka_proxy:
        condition: service_healthy
    networks:
      - fukuyoka

  db:
    image: fukuyoka_db:latest
    build:
      dockerfile: docker/db/Dockerfile
    container_name: fukuyoka_db
    env_file:
      - .env
    volumes:
      - ./scripts/pg_vector:/scripts:ro
    restart: unless-stopped
    networks:
      fukuyoka:
        ipv4_address: 192.168.100.11
