services:
  fukuyoka_frontend:
    environment:
      HUGO_ENV: development
    command: server --bind 0.0.0.0 --port 1313 --baseURL http://localhost:51841 --appendPort=false

  fukuyoka_proxy:
    ports:
      - "51841:80"

  cloudflared:
    profiles:
      - production
