services:
  fukuyoka_frontend:
    environment:
      HUGO_ENV: development
    command: --watch --baseURL http://localhost:51841
    restart: unless-stopped

  fukuyoka_proxy:
    ports:
      - "51841:80"
    depends_on:
      fukuyoka_frontend:
        condition: service_started
      fukuyoka_app:
        condition: service_started

  cloudflared:
    profiles:
      - production
